name: workoneerweb
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  intl_phone_field: ^3.0.0
  responsive_framework: ^0.1.9
  steps_indicator: ^1.3.0
  firebase_core: ^2.3.0
  firebase_database: ^10.0.6
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.3.0
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  firebase_storage: ^11.0.0
  uuid: any
  dio: ^4.0.6
  provider: ^6.0.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_messaging: ^14.2.1
  carousel_slider: ^4.1.1
  video_player: ^2.4.5
  chewie: ^1.3.4
  dotted_border: ^2.0.0+3
  shared_preferences: ^2.1.0
  dartz: ^0.10.1
  go_router: ^4.5.0
  fake_cloud_firestore: ^2.1.0
  connectivity_plus: ^2.3.9
  get_it: ^7.6.0
  flutter_html: ^3.0.0-alpha.6
  universal_html: ^2.2.2
  image_picker_web: ^2.0.3
  image_picker_for_web: ^2.1.12
  image_picker: ^0.8.7+1
  mockito: ^5.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any
  hive_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Marcellus
      fonts:
        - asset: assets/fonts/marcellus-regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
